{
 "title": "Trojan-Go Dashboard",
 "time": { "from": "2020-10-19T08:51:11.485Z", "to": "2020-10-19T08:56:11.485Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "upload_traffic_total",
   "type": "graph",
   "description": "upload traffic total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trojan_go_upload_traffic_bytes_total",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "download_traffic_total",
   "type": "graph",
   "description": "download traffic total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trojan_go_download_traffic_bytes_total",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "current_upload_speed",
   "type": "graph",
   "description": "current upload speed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trojan_go_current_upload_speed", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "current_download_speed",
   "type": "graph",
   "description": "current download speed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trojan_go_current_download_speed",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } }
 ]
}