apiVersion: v1
kind: Service
metadata:
  name: trojan-go-exporter-svc
  namespace: zidy
  labels:
    app: trojan-go-exporter-svc
spec:
  ports:
    - name: metrics
      port: 9550
      targetPort: metrics
  selector:
    app: trojan-go-exporter
